#!/usr/bin/env bash
# Install the training stack on a machine with a small home quota.
#
#   PREFIX=/scratch/$USER ./setup_lowdisk.sh          # everything on scratch
#   SYSTEM_TORCH=1 ./setup_lowdisk.sh                 # reuse a module's torch
#
# Three things blow a 10 GB quota, and this handles all of them:
#   pip's download cache (~3.5 GB)  -> PIP_CACHE_DIR under PREFIX, plus
#                                      --no-cache-dir so nothing is kept
#   the HF model cache (6.2 GB for  -> HF_HOME under PREFIX
#     Qwen2.5-3B, 2.1 GB 4-bit)
#   the venv itself (~5.5-6 GB)     -> PREFIX/venv, or skipped entirely with
#                                      SYSTEM_TORCH=1
#
# Writes PREFIX/env.sh — source it in every later shell (and in your job
# script) or the caches silently default back to $HOME and you are over quota
# again.
set -euo pipefail

PREFIX=${PREFIX:-$HOME/pdfbm-train}
SYSTEM_TORCH=${SYSTEM_TORCH:-0}
# e.g. https://download.pytorch.org/whl/cu121 to match an older cluster driver.
TORCH_INDEX=${TORCH_INDEX:-}
REPO_DIR=${REPO_DIR:-$(cd "$(dirname "$0")/../.." && pwd)}

say() { printf '\n== %s\n' "$1"; }

mkdir -p "$PREFIX"
# Resolve to a real path so env.sh is safe to source from anywhere.
PREFIX=$(cd "$PREFIX" && pwd)

avail=$(df -Ph "$PREFIX" 2>/dev/null | awk 'NR==2{print $4}')
say "installing under $PREFIX (avail: ${avail:-unknown})"
if [ "$PREFIX" = "$HOME/pdfbm-train" ]; then
    echo "NOTE: PREFIX is inside \$HOME, so this counts against your quota."
    echo "      If probe_env.sh found writable scratch, use PREFIX=/scratch/\$USER."
fi

mkdir -p "$PREFIX"/{cache/pip,cache/hf,tmp}

cat > "$PREFIX/env.sh" <<EOF
# Source this before installing or training. Generated by setup_lowdisk.sh.
export PDFBM_PREFIX="$PREFIX"
export PIP_CACHE_DIR="$PREFIX/cache/pip"
export HF_HOME="$PREFIX/cache/hf"
export TMPDIR="$PREFIX/tmp"
# Only the weights are wanted on disk, not a second copy in a stale layout.
export HF_HUB_DISABLE_TELEMETRY=1
# An \`if\` rather than \`[ -f ] && .\`: the latter returns non-zero when the venv
# is not built yet, which aborts any \`set -e\` script that sources this.
if [ -f "$PREFIX/venv/bin/activate" ]; then
    . "$PREFIX/venv/bin/activate"
fi
EOF
echo "wrote $PREFIX/env.sh"

# shellcheck disable=SC1090
. "$PREFIX/env.sh"

say "virtualenv"
if [ ! -d "$PREFIX/venv" ]; then
    if [ "$SYSTEM_TORCH" = "1" ]; then
        # Inherit the module/conda torch instead of downloading our own ~6 GB.
        python3 -m venv --system-site-packages "$PREFIX/venv"
    else
        python3 -m venv "$PREFIX/venv"
    fi
fi
# shellcheck disable=SC1091
. "$PREFIX/venv/bin/activate"
python -m pip install --no-cache-dir -q --upgrade pip

if [ "$SYSTEM_TORCH" = "1" ]; then
    say "checking the inherited torch"
    python - <<'PY'
import sys
try:
    import torch
except ImportError:
    sys.exit("SYSTEM_TORCH=1 but torch is not importable — load the module "
             "first (e.g. `module load pytorch`) and re-run")
print(f"torch {torch.__version__} (cuda {torch.version.cuda}) — reusing it")
PY
    say "installing only the light deps"
    # Everything from requirements.txt except torch, which we just inherited.
    python -m pip install --no-cache-dir -q \
        "transformers>=4.48" "datasets>=3.0" "accelerate>=1.0" \
        "peft>=0.14" "trl>=0.17" "bitsandbytes>=0.45" \
        "gguf>=0.10" "sentencepiece>=0.2"
else
    say "installing the full stack (~5.5-6 GB, no cache kept)"
    if [ -n "$TORCH_INDEX" ]; then
        python -m pip install --no-cache-dir -q --index-url "$TORCH_INDEX" torch
    fi
    python -m pip install --no-cache-dir -q -r "$REPO_DIR/training/requirements.txt"
fi

say "footprint"
du -sh "$PREFIX/venv" 2>/dev/null || true
du -sh "$PREFIX/cache/hf" 2>/dev/null || true
du -sh "$PREFIX" 2>/dev/null || true
python -c "import torch; print('cuda available:', torch.cuda.is_available())" 2>/dev/null || true

cat <<EOF

== done
Source the env in every new shell (and inside your job script):
    . $PREFIX/env.sh

Then train with the 4-bit base to keep the model cache at ~2.1 GB instead of
6.2 GB:
    python $REPO_DIR/training/finetune.py dataset/ -o $PREFIX/checkpoints/outline-lora-8k \\
        --base-model unsloth/Qwen2.5-3B-Instruct-bnb-4bit --max-seq-len 8192

See training/REMOTE.md ("Low-disk remote") for the disk budget and caveats.
EOF
